package CalculatorApp;


/**
* CalculatorApp/calculator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculatorApp.idl
* Monday, 29 August, 2022 2:39:39 PM IST
*/

public interface calculator extends calculatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface calculator
