package CalculatorApp;


/**
* CalculatorApp/calculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculatorApp.idl
* Monday, 29 August, 2022 2:39:39 PM IST
*/

public interface calculatorOperations 
{
  double getSum (double a, double b);
  double getDifference (double a, double b);
  double getProduct (double a, double b);
  double getQuotient (double a, double b);
} // interface calculatorOperations
