package CalculatorApp;

/**
* CalculatorApp/calculatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculatorApp.idl
* Monday, 29 August, 2022 2:39:39 PM IST
*/

public final class calculatorHolder implements org.omg.CORBA.portable.Streamable
{
  public CalculatorApp.calculator value = null;

  public calculatorHolder ()
  {
  }

  public calculatorHolder (CalculatorApp.calculator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalculatorApp.calculatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalculatorApp.calculatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalculatorApp.calculatorHelper.type ();
  }

}
